[package]
name = "flowistry_ifc"
version = "0.5.27"
edition = "2021"
publish = false

[package.metadata.rust-analyzer]
rustc_private = true

[dependencies]
flowistry = {version = "0.5.27", path = "../flowistry"}
rustc_plugin = {version = "0.5.27", path = "../rustc_plugin"}
env_logger = "0.9"
termcolor = "1.1"
anyhow = "1"
log = "0.4"